### ISSUE TITLE
Make TimePopover times clickable

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu.me#23]
Sometimes, I would rather click on a visible time than scroll to it. Click should scroll to clicked time.

**Comment by cpwallah** [comment]
hi i would kike to work on this issue @steida

**Comment by steida** [comment]
@cpwallah Great! Then `<Text key={hour} style={styles.hour}>` and `<Text key={minute} style={styles.minute}>` should be wrapped with Pressable, and should scroll on press. Thank you!
